// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appUser/": {
            "post": {
                "description": "Autentica a un usuario y devuelve un token de acceso y los detalles del usuario.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticación"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales del usuario",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Respuesta exitosa con token y detalles del usuario",
                        "schema": {
                            "$ref": "#/definitions/views.Response"
                        }
                    },
                    "400": {
                        "description": "Error: Datos inválidos o problema con el formato del email"
                    },
                    "401": {
                        "description": "Error: Credenciales incorrectas o intento de inicio de sesión fallido"
                    },
                    "500": {
                        "description": "Error interno del servidor"
                    }
                }
            }
        }
    },
    "definitions": {
        "swagger.LoginForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "userNameApp": {
                    "type": "string"
                }
            }
        },
        "views.Response": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "failedAttempts": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
